version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: leafvision-mysql
    restart: always
    networks:
      - leafvision-network
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: leaf_boss
    volumes:
      - mysql-data:/var/lib/mysql

  backend:
    image: yangshengzhou/leafvision:backend-v1
    container_name: leafvision-backend
    restart: always
    networks:
      - leafvision-network
    depends_on:
      - mysql
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/leaf_boss?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 123456

  frontend:
    image: yangshengzhou/leafvision:frontend-v1
    container_name: leafvision-frontend
    restart: always
    networks:
      - leafvision-network
    depends_on:
      - backend
    ports:
      - "80:80"

networks:
  leafvision-network:

volumes:
  mysql-data:
